name: Deploy docs
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: DonsWayo/capacitor-firebase
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn deploy:docs
        BUILD_DIR: docs/docs/.vuepress/dist/
